name: Build Server (Debug Only)
on:
  workflow_dispatch:

jobs:
  models:
    name: Download Model Files
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Model Files
        id: models
        run: |
          VERSION=$(awk -F ' = "' '/version =/ {print $2}' src-python/pyproject.toml | tr -d '"')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          mkdir -p src-python/models && cd src-python/models
          BASE_URL="https://github.com/idootop/TinyFace/releases/download/models-1.0.0"
          curl -# -O -L "${BASE_URL}/arcface_w600k_r50.onnx"
          curl -# -O -L "${BASE_URL}/gfpgan_1.4.onnx"
          curl -# -O -L "${BASE_URL}/inswapper_128_fp16.onnx"
          curl -# -O -L "${BASE_URL}/scrfd_2.5g.onnx"
          cd ${{ github.workspace }}
      - name: Upload models
        uses: actions/upload-artifact@v4
        with:
          name: models
          path: src-python/models
          if-no-files-found: error
    outputs:
      version: ${{ steps.models.outputs.version }}

  build-for-windows:
    name: Windows
    needs: models
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            build: windows
            os: windows-latest
            arch: x86_64
            runtime: directml
            bundle_cuda: false
          - target: x86_64-pc-windows-msvc
            build: windows
            os: windows-latest
            arch: x86_64
            runtime: cuda
            bundle_cuda: true

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Download Models
        uses: actions/download-artifact@v4
        with:
          name: models
          path: src-python/models
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"
      - name: Install Python Dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r src-python/requirements.txt
          python -m pip install -e src-python --no-deps

          if ("${{ matrix.bundle_cuda }}" -eq "true") {
            ./scripts/install-windows-ort.ps1 `
              -Runtime "${{ matrix.runtime }}" `
              -BundleCudaDependencies
          } else {
            ./scripts/install-windows-ort.ps1 `
              -Runtime "${{ matrix.runtime }}"
          }
      - name: Build Server
        shell: pwsh
        run: |
          ./scripts/build-windows-server.ps1 `
            -Runtime "${{ matrix.runtime }}" `
            -ConsoleMode force `
            -ArchiveSuffix "_debug"
      - name: Upload Server
        uses: actions/upload-artifact@v4
        with:
          name: server_${{ matrix.build }}_${{ matrix.arch }}_${{ matrix.runtime }}_debug
          path: out/*.zip
          if-no-files-found: error
